global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ['piews-backend.onrender.com']