name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    outputs:
      run_pipeline: ${{ steps.check.outputs.run_pipeline }}
    steps:
      - name: Check commit message
        id: check
        run: |
          echo "run_pipeline=${{ contains(github.event.head_commit.message, '[run-ci]') }}" >> $GITHUB_OUTPUT

  backend:
    needs: check_commit_message
    if: needs.check_commit_message.outputs.run_pipeline == 'true'
    name: Backend CI
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
            if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json not found in ./backend"
            exit 1
            fi
            npm install
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # Step 4: Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      # Step 5: Run API tests
      - name: Run API tests
        working-directory: ./backend
        env:
            MONGO_URI: mongodb://localhost:27017/testdb
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run test:api

      # Step 6: Run SonarQube analysis for backend
      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./backend
          args: >
            -Dsonar.projectKey=AdityaHosur_Peiws
            -Dsonar.organization=adityahosur
            -Dsonar.host.url=https://sonarcloud.io


  frontend:
    needs: check_commit_message
    if: needs.check_commit_message.outputs.run_pipeline == 'true'
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
            if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json not found in ./backend"
            exit 1
            fi
            npm install

      # Step 4: Run frontend tests
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test

      # Step 5: Run E2E tests
      - name: Run E2E tests
        working-directory: ./frontend
        run: npm run test:e2e

      # Step 6: Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: CI=false npm run build

      # Step 7: Run SonarQube analysis for frontend
      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./backend
          args: >
            -Dsonar.projectKey=AdityaHosur_Peiws
            -Dsonar.organization=adityahosur
            -Dsonar.host.url=https://sonarcloud.io

  docker-build:
    needs: [frontend, backend, check_commit_message]
    if: github.ref == 'refs/heads/main' && needs.check_commit_message.outputs.run_pipeline == 'true'
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peiws-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peiws-frontend:latest

      - name: Build and push Prometheus image
        uses: docker/build-push-action@v4
        with:
          context: ./monitor
          file: ./monitor/Dockerfile.prometheus
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peiws-prometheus:latest

      - name: Build and push Grafana image
        uses: docker/build-push-action@v4
        with:
          context: ./monitor
          file: ./monitor/Dockerfile.grafana
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/peiws-grafana:latest


  deploy:
    needs: docker-build
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook (Backend)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
          
      - name: Trigger Render Deploy Hook (Frontend)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}

      - name: Trigger Render Deploy Hook (Prometheus)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_PROMETHEUS }}
          
      - name: Trigger Render Deploy Hook (Grafana)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_GRAFANA }}
